FamilySearch/pewpew

lib/config/src/lib.rs

Fix issue with conditional compilation causing

---

.github/workflows/release.yml

Update release action to build and upload the

---

Cargo.lock
lib/mod_interval/src/lib.rs
src/lib.rs
src/request.rs
src/request/request_maker.rs

"endpoint delayed waiting for provider"

Reduce the amount of warning messages about

---

.github/actions/linux-x86_64-musl/Dockerfile
.github/workflows/pr.yml
.github/workflows/update-guide.yml
Cargo.lock
Cargo.toml
README.md
deny.toml
guide/src/config/providers-section.md
lib/channel/Cargo.toml
lib/channel/src/hash_set.rs
lib/channel/src/lib.rs
lib/config/Cargo.toml
lib/config/src/expression_functions.rs
lib/config/src/from_yaml.rs
lib/config/src/lib.rs
lib/config/src/select_parser.rs
lib/hdr-histogram-wasm/Cargo.toml
lib/test_common/Cargo.toml
src/lib.rs
src/providers.rs
src/providers/line_reader.rs
src/request.rs
src/request/body_handler.rs
src/request/response_handler.rs
src/util.rs

refactoring of the channels module to improve the intent of the code.

Add in unique providers. Also do some

---

README.md
guide/src/config/endpoints-section.md
lib/config/src/lib.rs

Add in the ability for `peak_load` to have a

---

.cargo/config
.github/actions/linux-x86_64-musl/Dockerfile
.github/workflows/pr.yml
.github/workflows/release.yml
Cargo.lock
README.md
pr.sh

- [Updated Docker to use Ubuntu 20.04](https://github.com/FamilySearch/pewpew/commit/1bc43de87c31965e966696b414514ebbf7dd23ab)
- [Added aarch64 and arm7 builds to the release](https://github.com/FamilySearch/pewpew/commit/6497db0e06c8bf88ab3699d637f3b07247a48ba2)
- [Added a build step to the PR to also build all releases](https://github.com/FamilySearch/pewpew/commit/70db0021ad20b71566e86b69f238e2e557894862)

Graviton2 arm build

---

.github/workflows/release-test-server.yml
.github/workflows/release.yml
pr.sh

- [Updated the test-server to also release arm builds](https://github.com/FamilySearch/pewpew/commit/959422821bb510921e40e30f5e8670052689153b)
- [Updated the release flow to remove -musl from the compressed name](https://github.com/FamilySearch/pewpew/commit/3e101ff3dc72fd833c6257229b39d82c5ed718af)

Arm test server

---

guide/results-viewer-react/src/components/TestResults/index.tsx

- The filter is now smarter and no longer regenerates the overall summary unless the filtered list changes
- Display the filtered endpoints only, unless the filtered is empty, then display all

Added code to also filter the displayed endpoints

---

guide/results-viewer-react/src/components/TestResults/index.tsx

- Fixed a typo where we weren't correctly checking changes to filtered length
- Fixed the tag display on filtered when showing all
- Fixed a bug where we wouldn't redraw the summary chart if the number of datapoints didn't change

Fixed more bugs in the Results Viewer

---

.github/workflows/pr.yml
Cargo.lock
Cargo.toml
guide/results-viewer-react/package-lock.json
guide/results-viewer-react/package.json

- [Updated dependencies](https://github.com/FamilySearch/pewpew/pull/117/commits/986e471ac59dee323c71cf33ab5f4fdcc5c101b0)
- [Removed macos-11 from the test matrix](https://github.com/FamilySearch/pewpew/pull/117/commits/a82695dccdc4297a3a273cca96166f21c2612da4)

Update dependencies 20230421

---

.devcontainer/Dockerfile
.github/workflows/pr-js.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/update-guide.yml
guide/results-viewer-react/package-lock.json
guide/results-viewer-react/package.json

- [Fixed the HDR Histogram build for webpack](https://github.com/FamilySearch/pewpew/commit/62ce7cb5d9b6507d8a698628cd2cebfd59ec2b4d)
- https://github.com/rustwasm/wasm-bindgen/issues/3276#issuecomment-1475805578
- https://github.com/rustwasm/wasm-pack/pull/1224
- [Updated Viewer dependencies](https://github.com/FamilySearch/pewpew/commit/00fbb2aa293937f5a005a4fea6cdb84ad1d8614d)

Fix histogram

---

Cargo.toml
guide/src/cli.md
src/bin/pewpew.rs
src/lib.rs

- Cargo Version Upgrade
- Updates the guide to include new flag
- Adds the ability to include skipBody argument in the CLI
- Changes added to test the new argument

Adds skipBody CLI argument - Skips Request and Response Body in Try Output

---

guide/src/cli.md
lib/config/src/configv2/endpoints.rs
lib/config/src/configv2/load_pattern.rs
lib/config/src/configv2/providers.rs
lib/config/src/configv2/providers/file.rs
lib/config/src/shared.rs
src/bin/pewpew.rs
src/lib.rs

- Merged master into scripting branch to merge new --skipBody option.

Skip body scripting

---

.devcontainer/Dockerfile
.github/workflows/pr-js.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/update-guide.yml
Cargo.lock
Cargo.toml
guide/results-viewer-react/package-lock.json
guide/results-viewer-react/package.json
lib/body_reader/Cargo.toml
lib/config-wasm/Cargo.toml
lib/config-wasm/tests/package-lock.json
lib/config/Cargo.toml
lib/hdr-histogram-wasm/tests/package-lock.json
src/stats.rs

Updating dependencies to release https://github.com/FamilySearch/pewpew/pull/140
- [Updated dependencies and fixed deprecations](https://github.com/FamilySearch/pewpew/pull/143/commits/cd0895abc654bfff31521488c7bb08229f03db37)
- [Updated Wasm-pack to match the version in the 0.6.0 scripting branch](https://github.com/FamilySearch/pewpew/pull/143/commits/32f7cddbd5826b1f871555507814bd03a23d13f5)

Updated dependencies and fixed deprecations

---

README.md
lib/config-wasm/tests/test.js

- [Added additional tests for all the example yaml files](https://github.com/FamilySearch/pewpew/commit/fcc04b6cd585ec70708014cb7c5af04d2a4e822e)
- [Updated the README for the current changes](https://github.com/FamilySearch/pewpew/commit/6fe6df8ca1c48bc6abb5feac8236b65b781628ae)

Example wasm tests

---

Cargo.lock
agent/createtest/createtest.scripting.yaml
agent/createtest/createtest.yaml
agent/createtest/shorter/createtest.scripting.yaml
agent/createtest/shorter/createtest.yaml
common/src/util/s3.ts
common/src/util/sqs.ts
common/src/util/util.ts
common/test/scriptingwithvars.yaml
controller/components/YamlViewer/story.tsx
controller/test/basicwithenv.yaml
guide/results-viewer-react/package-lock.json
guide/results-viewer-react/src/components/YamlViewer/story.tsx
lib/config-wasm/tests/test.js

- [Removed unneeded vars](https://github.com/FamilySearch/pewpew/commit/eb6b123e7cb5b0977edd799deb235dc15879d83c)
- [Added mock restore](https://github.com/FamilySearch/pewpew/commit/7d92f2f59804345569fdb6d8a38e7ab14ad965a1)
- [Fixed grouping of tests into describe](https://github.com/FamilySearch/pewpew/commit/cd9b88742267dfe2656afaa0b483fc3dae1defaf)
- [Added AGENT_APPLICATION_NAME similar to the controller name](https://github.com/FamilySearch/pewpew/commit/2937b260cec273a823d67ed9f8764ea2c6c5512d)
- [Removed unneeded comment](https://github.com/FamilySearch/pewpew/commit/50accb633ca18149b8e02abb53b995625e61a34b)
- [Removed additional unneeded vars](https://github.com/FamilySearch/pewpew/commit/a4a55e05c1bb396d2e85dd8321eee733ac367e9d)

Fix tests scripting

---

agent/package.json
common/package.json
controller/README.md
controller/components/StartTestForm/index.tsx
controller/next.config.js
controller/package.json
controller/pages/api/util/clientutil.ts
controller/pages/login.tsx
package-lock.json
package.json

- [Updated version and dependencies](https://github.com/FamilySearch/pewpew/commit/7d862358117c65d59f7bca8bc262b930e86fa00d)
- [Removed old command from README](https://github.com/FamilySearch/pewpew/commit/ccac328aec7665fad6714619db88b3a0b078c338)
- [Removed references to fsdpt.org](https://github.com/FamilySearch/pewpew/commit/6c6837bd645bb089f39e9137138b91a761c9e595)
- [Removed unneeded vars and added missing ones](https://github.com/FamilySearch/pewpew/commit/0e850a12437ac53eaf642306d08695f3470e9263)
Acceptance Tests:
Coverage Tests:

Updates on master PPaaS

---

controller/components/TestInfo/index.tsx

- [Removed links to Splunk that shouldn't be in OpenSource](https://github.com/FamilySearch/pewpew/pull/158) merge into scripting branch

Remove splunk links scripting

---

guide/results-viewer-react/package-lock.json

- [Changed agent version greaterthan to use semver](https://github.com/FamilySearch/pewpew/commit/866c312cef174b97c6e649bf456a204e7440df9a) - https://github.com/FamilySearch/pewpew/pull/160
- [Bump @babel/traverse in /guide/results-viewer-react](https://github.com/FamilySearch/pewpew/commit/fea2495ad52c0177e6902497457c0d517f1be4a5) - https://github.com/FamilySearch/pewpew/pull/161

Merge from master

---

.github/workflows/pr-ppaas.yml
lib/config-wasm/tests/package-lock.json
lib/hdr-histogram-wasm/tests/package-lock.json
package-lock.json

- Bumps [rustix](https://github.com/bytecodealliance/rustix) from 0.37.23 to 0.37.25.  - https://github.com/FamilySearch/pewpew/pull/163
- [Release notes](https://github.com/bytecodealliance/rustix/releases)
- [Commits](https://github.com/bytecodealliance/rustix/compare/v0.37.23...v0.37.25)
- https://github.com/FamilySearch/pewpew/pull/164
- Updated lock files to fix audit vulnerabilities
- Updated pr flow to fix path

Dependebot scripting

---

.github/workflows/pr-guide.yml
.github/workflows/pr-rust.yml
.github/workflows/update-guide.yml
Cargo.lock
common/.github/workflows/pr.yml
common/integration/sqs.spec.ts
common/src/s3file.ts
common/test/s3file.spec.ts
common/test/sqs.spec.ts
controller/pages/api/util/ppaasencrypts3file.ts
guide/results-viewer-react/package-lock.json
guide/results-viewer-react/package.json
lib/body_reader/src/lib.rs
package-lock.json
pr.sh
src/lib.rs

- [Updated cargo lock file to latest versions](https://github.com/FamilySearch/pewpew/pull/166/commits/113799011b422a0b0b6279529fa93730348b9eaf)
- [Fixed Clippy warnings](https://github.com/FamilySearch/pewpew/pull/166/commits/be99f39eb29f4918f77ee3d9af035ce6a02d143e)
- [Updated the PPaaS lock file](https://github.com/FamilySearch/pewpew/pull/166/commits/087eb1d5fe075232f2718d17bf536d4002dc4f35)
- Fixed changes due to AWS SDK Changes on StorageClass
- [Updated the Guide lock file](https://github.com/FamilySearch/pewpew/pull/166/commits/7bb512ddcb551724f33e4b41cc614784f58c2f94)
- Removed support for Node 16 from guide
- [Removed Node 16.x from github actions](https://github.com/FamilySearch/pewpew/pull/166/commits/4c15025042090ce9f1f38335d49190d1eb4c1837)
Coverage Tests:
Acceptance Tests:

Update the world

---

.github/workflows/pr-guide.yml
.github/workflows/pr-rust.yml
.github/workflows/update-guide.yml
Cargo.lock
common/.github/workflows/pr.yml
common/integration/sqs.spec.ts
common/src/s3file.ts
common/test/s3file.spec.ts
common/test/sqs.spec.ts
controller/pages/api/util/ppaasencrypts3file.ts
guide/results-viewer-react/package-lock.json
guide/results-viewer-react/package.json
lib/body_reader/src/lib.rs
lib/config-gen/tests/package-lock.json
lib/scripting-macros/src/lib.rs
package-lock.json
pr.sh

- https://github.com/FamilySearch/pewpew/pull/166
- [updated root lock file and fixed clippy warnings](https://github.com/FamilySearch/pewpew/pull/167/commits/40fb07ce9e9398d52b401f7cb814b7d8ebd25e07)
Acceptance:
Coverage:

Update world scripting

---

.github/workflows/pr-rust.yml
.github/workflows/release.yml

- [Added Apple M1 Arm64 to the PR and Release flow](https://github.com/FamilySearch/pewpew/pull/174/commits/6383859b3db80f35f257f44f2d51f6c79fb9a76e)

Added Apple M1 Arm64 to the PR and Release flow

---

.github/workflows/pr-rust.yml
.github/workflows/release-test-server.yml
.github/workflows/release.yml

- https://github.com/FamilySearch/pewpew/pull/174
- https://github.com/FamilySearch/pewpew/pull/176

Apple m1 scripting

---

examples/provider_collect.yaml
examples/provider_loop_with_counter.yaml
examples/provider_spread.yaml
lib/channel/src/lib.rs
src/lib.rs

- [Simplified the provider names in example](https://github.com/FamilySearch/pewpew/commit/9dee4035f3981fa6e017086c43f4e3bea6498f8b)
- [Fixed the try hang for both provider_chain and provider spread](https://github.com/FamilySearch/pewpew/commit/fc767b63e45d1305f35a2a48e7e65a3f4ddfaf53)
- provider_loop still has issues with try scripts
- [Added example with provider collect](https://github.com/FamilySearch/pewpew/commit/49a3d68726c4bd83320f48f4c686a3b202611c3e)
- [Added additional logging to find try script issues with provider_loop example](https://github.com/FamilySearch/pewpew/commit/0388b69416ad34a6b03ee38cb6c159c4ce2ef312)

Pewpew try hang

---

.github/workflows/pr-ppaas.yml
agent/package.json
common/package.json
controller/package.json
package-lock.json
package.json

- https://github.com/FamilySearch/pewpew/pull/184
- [Updated version and dependencies for release of PPaaS](https://github.com/FamilySearch/pewpew/commit/c378bb1d4083361b501577069d5321802af661eb)
Acceptance:
Coverage:

Updated version and dependencies for release of PPaaS

---

agent/src/tests.ts
common/src/ppaass3message.ts
common/src/util/s3.ts
controller/integration/testscheduler.spec.ts
controller/pages/api/util/testscheduler.ts

- [Added extra locations that needed specific file tagging](https://github.com/FamilySearch/pewpew/commit/ef475c6f88cf5c47c8fbcac3c75bf06382213f61)
- [Added integration test for runHistoricalDelete](https://github.com/FamilySearch/pewpew/pull/191/commits/17e15772c5a9f35542e1af92d89b204c35b7d932)
- [Fixed another spot where we weren't adding the addional tags on all on copyObject](https://github.com/FamilySearch/pewpew/pull/191/commits/817f91f5c66c0fbb0750a0bf30de5705982c6d7d)
These were issues that were found while working on deploying the controller and agent and seeing what things were missed on getting tagged correctly.

Additional tagging changes found while deploying

---

agent/createtest/pewpewtest.spec.ts
agent/src/tests.ts
common/src/ppaass3message.ts
common/src/util/s3.ts
controller/integration/testscheduler.spec.ts
controller/pages/api/util/testscheduler.ts

- https://github.com/FamilySearch/pewpew/pull/191
- [Added the correct tagging to the pewpew scripting test upload](https://github.com/FamilySearch/pewpew/commit/98cb131ce5445b04647ed3e2d0416a51a90a0488)
- [Updated the scripting pewpew to the release version](https://github.com/FamilySearch/pewpew/commit/950564baad45edbab3c8e24efa37395a5f22854d)

Extra s3 tagging fixes scripting

---

.github/workflows/pr-guide.yml
.github/workflows/pr-ppaas.yml
.github/workflows/pr-rust.yml
.github/workflows/release-test-server.yml
.github/workflows/release.yml
.github/workflows/update-guide.yml
agent/.github/workflows/pr.yml
agent/package.json
common/.github/workflows/pr.yml
common/package.json
controller/.github/workflows/pr.yml
controller/acceptance/test.spec.ts
controller/package.json
controller/test/util.spec.ts
guide/results-viewer-react/package-lock.json
guide/results-viewer-react/package.json
package-lock.json
package.json
pr.sh

- https://github.com/FamilySearch/pewpew/pull/196
- Update lock file

Update dependencies20240227 scripting

---

.github/actions/linux-x86_64-musl/Dockerfile
.github/workflows/pr-guide.yml
.github/workflows/pr-ppaas.yml
.github/workflows/pr-rust.yml
.github/workflows/release-test-server.yml
.github/workflows/release.yml
.github/workflows/update-guide.yml
Cargo.lock
guide/results-viewer-react/package-lock.json
package-lock.json

- https://github.com/FamilySearch/pewpew/pull/198

Replace actions-rs with rustup in Scripting branch

---

.eslintrc
.gitignore
agent/test/pewpewtest.spec.ts
controller/components/PewPewVersions/index.tsx
controller/components/PewPewVersions/initialProps.ts
controller/components/PewPewVersions/story.tsx
controller/components/StartTestForm/index.tsx
controller/components/StartTestForm/story.tsx
controller/components/TestInfo/index.tsx
controller/components/Toaster/index.tsx
controller/components/Toaster/story.tsx
controller/integration/pewpew.spec.ts
controller/pages/admin.tsx
controller/pages/api/util/pewpew.ts
controller/test/pewpew.spec.ts
guide/results-viewer-react/.eslintrc
guide/results-viewer-react/src/components/Modal/story.tsx
guide/results-viewer-react/src/components/YamlUrls/story.tsx

Merge the changes from these two PRs into our scripting branch.
- https://github.com/FamilySearch/pewpew/pull/201
- https://github.com/FamilySearch/pewpew/pull/204
@bryan-e-lopez There doesn't seem to be any conflicts, so we can just merge this in then add the additional code with a separate PR.

Pewpew "latest" version view into scripting.

---

controller/integration/pewpew.spec.ts
controller/pages/api/util/pewpew.ts
controller/test/pewpew.spec.ts

- Unit and Integration tests were not catching the bug, fixed the tests, then fixed the code

Fixed the getTags call to get the latest tags

---

.eslintrc
controller/acceptance/healthcheck.spec.ts
controller/acceptance/pewpew.spec.ts
controller/acceptance/queues.spec.ts
controller/acceptance/test.spec.ts
controller/components/YamlWriterUpload/index.tsx
guide/results-viewer-react/.eslintrc
guide/results-viewer-react/src/components/YamlWriterUpload/index.tsx
pr.sh

- https://github.com/FamilySearch/pewpew/pull/214

Update pr script scripting

---

.github/workflows/pr-guide.yml
.github/workflows/pr-ppaas.yml
.github/workflows/pr-rust.yml
agent/.github/workflows/pr.yml
agent/createtest/pewpewtest.spec.ts
agent/package.json
agent/src/tests.ts
common/.github/workflows/pr.yml
common/package.json
common/src/util/ec2.ts
controller/.github/workflows/pr.yml
controller/package.json
controller/pages/_document.tsx
package-lock.json
package.json

- [Updated version and dependencies](https://github.com/FamilySearch/pewpew/commit/cbef757660f9120a741d5dc293b6e5537ddc3267)
- Updated Storybook and Axios versions
- [Simplified _document for styled-components](https://github.com/FamilySearch/pewpew/commit/57aae511c133764ca0c83f6ec47b7c343248f62b)
- [Added code to upload pewpew for the agent tests if it's not already there.](https://github.com/FamilySearch/pewpew/pull/223/commits/6ce0c3a3531a340d4a9c1d4141a1f8e390957100)
- [Updated PR flows to add Node v22 testing](https://github.com/FamilySearch/pewpew/pull/223/commits/04549ca253d29daec03d8254a858a21ba668a4ea)
- [Removed reference to IMDSv1 command since we're not using it](https://github.com/FamilySearch/pewpew/pull/223/commits/7954acc10ea7454277964fe4ad82752fb2d57e99)
Coverage Tests: …

Update Dependencies 2024-05-29

---

.github/workflows/pr-guide.yml
.github/workflows/pr-ppaas.yml
.github/workflows/pr-rust.yml
agent/.github/workflows/pr.yml
agent/createtest/pewpewtest.spec.ts
agent/package.json
agent/src/tests.ts
common/.github/workflows/pr.yml
common/package.json
common/src/util/ec2.ts
controller/.github/workflows/pr.yml
controller/package.json
controller/pages/_document.tsx
package-lock.json
package.json

- https://github.com/FamilySearch/pewpew/pull/221
- https://github.com/FamilySearch/pewpew/pull/223

Scripting update 2024-05-29

---

.github/workflows/pr-guide.yml
.github/workflows/pr-ppaas.yml
.github/workflows/pr-rust.yml
agent/.github/workflows/pr.yml
agent/createtest/pewpewtest.spec.ts
agent/package.json
agent/src/tests.ts
common/.github/workflows/pr.yml
common/package.json
common/src/ppaasteststatus.ts
common/src/util/ec2.ts
common/src/util/s3.ts
controller/.github/workflows/pr.yml
controller/package.json
controller/pages/_document.tsx
package-lock.json
package.json

- https://github.com/FamilySearch/pewpew/pull/221
- https://github.com/FamilySearch/pewpew/pull/223

Merge master into Scripting branch

---

Cargo.lock
Cargo.toml
deny.toml
lib/test_common/Cargo.toml
lib/test_common/test_common.rs
src/bin/test_server.rs
src/lib.rs
src/request.rs
src/request/request_maker.rs
src/request/response_handler.rs
src/util.rs
tests/integration.rs

Summary: Merged the [237](https://github.com/FamilySearch/pewpew/pull/237) PR into the scripting branch
- [Merge branch 'master' into update-rust-dependencies-scripting-2024-08-01-hyper](https://github.com/FamilySearch/pewpew/pull/242/commits/357c4c5e298ed9911a6d68f6412621d862df8e6e)
- [Fixed comments from merge](https://github.com/FamilySearch/pewpew/pull/242/commits/844103c69420f91f2f138844fe537a472e244097)

Update rust dependencies scripting 2024-08-01 hyper/http

---

guide/results-viewer-react/src/components/YamlWriterForm/writeyaml.ts

The Har to Yaml converter was generating bad Yamls. This PR handles edge cases so that the results are clean and functional.

Fixed errors in har to yaml generator

---

guide/results-viewer-react/src/components/YamlEndpoints/index.tsx
guide/results-viewer-react/src/components/YamlUrls/index.tsx
guide/results-viewer-react/src/components/YamlWriterUpload/index.tsx

The Har-to-Yaml flow had the following defects:
- The contents of the Upload Files modal were overflowing
- The contents of the Customize HAR File modal were overflowing
- All of the URLs from the Har file were opening modals all at once
This PR fixes these defects.
Here's [the Jira ticket](https://icseng.atlassian.net/browse/PERF-1903)

Fixes to defects in the har to yaml flow

---

guide/results-viewer-react/src/components/Icons/AddIcon.tsx
guide/results-viewer-react/src/components/Icons/DeleteIcon.tsx
guide/results-viewer-react/src/components/Icons/EditIcon.tsx
guide/results-viewer-react/src/components/Icons/XIcon.tsx
guide/results-viewer-react/src/components/Modal/index.tsx
guide/results-viewer-react/src/components/ToggleDefaults/ToggleDefaults.tsx
guide/results-viewer-react/src/components/YamlEndpoints/index.tsx
guide/results-viewer-react/src/components/YamlLoadPatterns/index.tsx
guide/results-viewer-react/src/components/YamlLoadPatterns/story.tsx
guide/results-viewer-react/src/components/YamlLoggers/index.tsx
guide/results-viewer-react/src/components/YamlLoggers/story.tsx
guide/results-viewer-react/src/components/YamlProviders/File.tsx
guide/results-viewer-react/src/components/YamlProviders/List.tsx
guide/results-viewer-react/src/components/YamlProviders/Range.tsx
guide/results-viewer-react/src/components/YamlProviders/Response.tsx
guide/results-viewer-react/src/components/YamlProviders/index.tsx
guide/results-viewer-react/src/components/YamlStyles/index.tsx
guide/results-viewer-react/src/components/YamlStyles/story.tsx
guide/results-viewer-react/src/components/YamlUrls/HeadersView.tsx
guide/results-viewer-react/src/components/YamlUrls/QueryParamsView.tsx
guide/results-viewer-react/src/components/YamlUrls/RequestDetailsTabs.tsx
guide/results-viewer-react/src/components/YamlUrls/index.tsx
guide/results-viewer-react/src/components/YamlVars/VarInput.tsx
guide/results-viewer-react/src/components/YamlVars/index.tsx
guide/results-viewer-react/src/components/YamlVars/story.tsx
guide/results-viewer-react/src/components/YamlWriterForm/index.tsx
guide/results-viewer-react/src/components/YamlWriterUpload/index.tsx

Overhauls the styles of buttons and input. Replaces "Default" checkboxes with buttons.
https://icseng.atlassian.net/browse/PERF-1929

Style improvements for buttons and inputs

---

Cargo.lock
agent/package.json
agent/src/pewpewtest.ts
agent/src/tests.ts
agent/test/mock.ts
common/package.json
common/test/mock.ts
controller/components/LinkButton/index.tsx
controller/package.json
controller/test/mock.ts
lib/body_reader/src/lib.rs
lib/config/src/configv1/expression_functions.rs
package-lock.json
package.json
src/providers/json_reader.rs
src/providers/line_reader.rs

- https://github.com/FamilySearch/pewpew/pull/299
- https://github.com/FamilySearch/pewpew/pull/300
- https://github.com/FamilySearch/pewpew/pull/301
- https://github.com/FamilySearch/pewpew/pull/302
- https://github.com/FamilySearch/pewpew/pull/303
Coverage Tests:

Update node dependencies scripting 2025 04 11

---

guide/results-viewer-react/src/components/YamlWriterUpload/index.tsx

This addresses the following Jiras:
- https://icseng.atlassian.net/browse/PERF-2181
- https://icseng.atlassian.net/browse/PERF-2182

Updates to filter and select/deselect URLs in HAR to Yaml

---

Cargo.lock
Cargo.toml
deny.toml
lib/body_reader/Cargo.toml
lib/config-gen/.cargo/config.toml
lib/config-gen/tests/package-lock.json
lib/config-gen/tests/package.json
lib/config-gen/tests/test.js
lib/config-wasm/.cargo/config.toml
lib/config-wasm/Cargo.toml
lib/config/Cargo.toml
lib/config/src/configv1/expression_functions.rs
lib/config/src/configv1/mod.rs
lib/config/src/configv2/endpoints/declare.rs
lib/config/src/configv2/error.rs
lib/config/src/configv2/providers/list.rs
lib/config/src/configv2/query.rs
lib/config/src/configv2/scripting.rs
lib/config/src/configv2/templating.rs
lib/config/src/configv2/templating/parser.rs
lib/scripting-macros/src/lib.rs
src/lib.rs
src/providers.rs
src/providers/csv_reader.rs
src/providers/json_reader.rs
src/providers/line_reader.rs
src/request.rs
src/util.rs

- [Merge branch 'master' into update-rust-dependencies-scripting-2025-06-10](https://github.com/FamilySearch/pewpew/commit/8d14931f53b8926f9f3b2a2c2e22c89944e3c49b)
- https://github.com/FamilySearch/pewpew/pull/315
- [Fixed clippy warning](https://github.com/FamilySearch/pewpew/commit/d6310b182c25874ee21cad4dc41a293288d3febc)
- https://github.com/FamilySearch/pewpew/pull/307
- [Updated nom to latest](https://github.com/FamilySearch/pewpew/pull/316/commits/44ea3cb020c939d3d744a5ff5650d33cc24c07b7)
- [Updated config-gen tests to latest](https://github.com/FamilySearch/pewpew/pull/316/commits/5113608c355b0583ed02f98139a7d9a168614ae6)
- Should have been ported over as part of https://github.com/FamilySearch/pewpew/pull/305
- [Rolled back some lock file changes to match …

Update rust dependencies scripting 2025-06-10

---

Cargo.lock
src/README.md

- https://github.com/FamilySearch/pewpew/pull/318
- https://github.com/FamilySearch/pewpew/pull/319

Merge 5.14 release into scripting
