- .github/workflows/release.yml
that the version of the tag matches Cargo.toml, and also give it the
ability to handle building preview builds
> Update the GitHub action for releases to check

- .github/workflows/release.yml
which didn't account for the leading "v".
Also change it so the Cargo.toml version only needs to match the tag
version in non-prerelease releases.
> Fix previous issue in release GitHub action

- lib/config/src/lib.rs
- src/lib.rs
- tests/.gitattributes
- tests/integration.rs
its duration set to the duration of the test instead of for that segment
> Fix bug where each segment of a load pattern had

- lib/channel/src/lib.rs
- src/request.rs
- src/request/request_maker.rs
requests per endpoint and auto-
sized providers grow.
Previously the number of max parallel requests was determined based on
the maximum length of any `send: block` providers that endpoint provides
for, or the `max_parallel_requests` parameter, whichever is smaller.
Now, we instead take into consideration the maximum number of empty
slots in any `send:block` providers multiplied by a multiplier between
1 and 10. If any of the `send:block` providers are empty the multiplier
is incremented. If all of the providers are full the multiplier is
decremented.
For auto-sized providers, previously they would grow (the limit would
increment) whenever the provider is filled and then emptied and anytime
an endpoint determines it should be firing off a request but it was
waiting for a value from the …
> Tweak how we determine the limit for parallel

- README.md
- lib/mod_interval/src/lib.rs
sleep properly between endpoint calls, effectively disregarding any
load limits
> Fix regression in v0.5.6 where pewpew does not

- lib/channel/src/lib.rs
- src/lib.rs
- src/request.rs
- tests/int_on_demand.yaml
- tests/integration.rs
which broke `on_demand`, and was manifest most often by try runs hanging
Add integration test for on_demand
> Fix regression in earlier 0.5.8 preview builds

- .github/workflows/release-test-server.yml
- .github/workflows/release.yml
- lib/body_reader/src/lib.rs
- lib/channel/src/hash_set.rs
- lib/channel/src/lib.rs
- lib/config/src/lib.rs
- lib/config_wasm/src/lib.rs
- src/lib.rs
- src/providers.rs
- src/request/body_handler.rs
- src/stats.rs
- src/util.rs
I tested this out already by creating a `v0.0.0-test-release-ci-preview` tag and it looks like GitHub was able to go through the release CI without any problems. I will leave that release/tag up until you've verified then I will remove it.
One thing to note: I noticed when I pushed that tag to GitHub, I accidentally also pushed the `v0.5.8-preview3` tag. It seems that when you pushed out the tag, @tkmcmaster, my local repo fetched it, but then when you deleted it my local repo never did. I manually deleted it locally and re-deleted it on GitHub. 
[This](https://stackoverflow.com/questions/10491146/in-git-how-do-i-sync-my-tags-against-a-remote-server/49215190) seems relevant. By default VS Code does automatic `git fetch`es in the background which pulls down all the remote tags. We may want …
> Fix release ci

- Cargo.lock
- guide/serve-guide.sh
- lib/config_wasm/Cargo.toml
- lib/config_wasm/build-node.sh
- Fixed the config wasm build per the getrandom docs for javascript
- Fixed issues with running on WSL2 Ubuntu 20.04 which doesn't support SIGINT only INT
> Fix config wasm

- Cargo.lock
- lib/channel/src/lib.rs
- lib/config/src/expression_functions.rs
- lib/config/src/select_parser.rs
- src/lib.rs
- tests/integration.rs
https://github.com/FamilySearch/pewpew/issues/46
- Changed the integration test to turn on watch_config_file causes on_demand to fail
- Fixed the issue with --watch and on_demand
- When there was a "watcher" it would also add an on_demand listender which would catch the messages preventing the real endpoint from receiving the message and firing.
- We now only create a lisenter when something tries to listen (i.e. an endpoint). The config watcher never actually runs anything and therefor never "listens".
- Added config provider logging of on_demand counts.
> On demand issue46

- Cargo.lock
- lib/channel/src/lib.rs
- src/stats.rs
Commit https://github.com/FamilySearch/pewpew/commit/3aa591614ecb55309ee4fe4d8ab420abd0ffdc24 changed the name of the provider name from 'provider' to 'name' breaking
our agent dashboard. Reverted it to fix the dashboard.
> Reverted some of the name fixes due to Splunk Dashboard issues

- .github/workflows/update-guide.yml
- Cargo.lock
- Cargo.toml
- README.md
- Changed the guild release to use npm ci rather than install for continuous integration environments
- Updated the Readme to include the config parser fix
- Updated the cargo version in preparation for releasing 0.5.8!
> Update for release of 0.5.8

- .devcontainer/Dockerfile
- Cargo.lock
- Cargo.toml
- lib/body_reader/Cargo.toml
- lib/channel/Cargo.toml
- lib/config/Cargo.toml
- lib/config/src/from_yaml.rs
- lib/config/src/lib.rs
- lib/config/src/select_parser.rs
- lib/config_wasm/src/lib.rs
- lib/for_each_parallel/Cargo.toml
- lib/for_each_parallel/src/lib.rs
- lib/test_common/Cargo.toml
- src/bin/pewpew.rs
- src/bin/test_server.rs
- src/lib.rs
- src/providers.rs
- src/request.rs
- src/request/body_handler.rs
- src/request/request_maker.rs
- src/request/response_handler.rs
- src/stats.rs
- src/util.rs
- tests/integration.rs
I've got everything compiling and all the tests passing. Before I unmark this PR as a draft I want to run some benchmarks to see if newer versions of tokio, hyper, etc. noticeably impact performance.
> Upgrade tokio and other dependencies

- Cargo.lock
- README.md
- guide/src/cli.md
- lib/config-wasm/src/lib.rs
- lib/config/src/lib.rs
- lib/test_common/Cargo.toml
- lib/test_common/test_common.rs
- src/bin/pewpew.rs
- src/bin/test_server.rs
- src/lib.rs
- src/line_writer.rs
- src/providers.rs
- src/request.rs
- src/request/request_maker.rs
- src/stats.rs
- Added logging to the pewpew binary to trace the flow through the components
- Fixed a bug Jon found that we only log one header during a try script rather than all if there are duplicates. Changed the try run to log headers_all rather than headers
-  Changed the try script logger to use stdout instead of stderr
- Fixed the docs for try and run to show the change from 0.5.2 that stats go to stdout
-  Modified the Config WebAssembly (config-wasm) to also return file body paths from the endpoint body
> Binary logging

- deny.toml
- src/bin/pewpew.rs
- src/lib.rs
- [Fixed an issue with out directories and stats file params](https://github.com/FamilySearch/pewpew/commit/93346a3c00d96390eae2d708cce7e5adb648ca6f)
- new versions of Clap panic with invalid utf8 passed to value_of_os()
- https://github.com/clap-rs/clap/issues/3344
- [Added comments to changes](https://github.com/FamilySearch/pewpew/commit/b2793d5d40bdc25873302237359e937d6ec5c6d3)
- [Added tests for the command line parser](https://github.com/FamilySearch/pewpew/commit/0e8433ea7871a94dbe27944e1a096e81afbbbab7) 
- Split the parsing code into separate functions that can be tested
- Moved the logger init out of the match functions so we can test the cli parsing
- Added tests around the path checks. Found we weren't parsing the try -d the same and fixed it
- [Added additional tests for the …
> pewpew -d crash

- Cargo.lock
- Cargo.toml
- guide/src/cli.md
- src/bin/pewpew.rs
- src/lib.rs
Rewrites the command line argument parsing segment of the `pewpew` cli program; where the `clap` "builder" API was used previously, the "derive" form is now used.
As a part of this rewrite, the intended behavior of the `-i`/`--include` flag for the `try` subcommand was restored. Now, `-i x y z` is not valid, but `-i x -i y -i z` is. This also allows the positional argument for the config file to be placed after the include filters.
- The old, builder-focused, code was removed.
- Tests were rewritten, primarily to read an `ExecConfig` from the new derived parser, but tests that contained `--include _id=0 _id=1` or similar as arguments were rewritten to have `--include _id=0 --include _id=1`
- The examples of `--help` output in the book were also modified to be more in line with actual …
> Use clap derive, fixing behavior of `--include` flag.

- lib/zip_all/src/lib.rs
- pr.sh
The `zip_all_map` function is effectively the same as the existing `zip_all` function, but works with maps rather than lists. This can be used when multiple input provider streams are used, but it is also desired to track which specific provider a certain value came from.
This functionality was helpful in one of the prototypes for scripting that I'd built, and since it didn't hurt compatibility, I implemented it on its own for the  `0.5.x` versions.
Additionally, documentation comments/doctests were added to the existing ZipAll.
As one last small change `cargo test --all --doc` was added to `pr.sh` so that the doctests written for this PR, as well as any future doctests, will be ran as a part of the PR workflow.
> Add `zip_all_map` function to `zip_all` lib crate.

- Cargo.lock
- Cargo.toml
- src/bin/pewpew.rs
https://rustsec.org/advisories/RUSTSEC-2021-0145
This PR only removes the *direct* dependency on `atty`. The `pr.sh` script will still show the advisory warning, as the version of `env_logger` pulled in by `jsonpath_lib` (currently pinned to an older version for compatibility) does itself depend on `atty`.
With this PR, the MSRV will be upped to `Rust 1.70.0`.
> use IsTerminal trait (Rust 1.70.0), removing (direct) dependency on `atty` crate

- Cargo.lock
- lib/config/Cargo.toml
- lib/config/src/expression_functions.rs
The fix for updating `jsonpath_lib` to version `0.3.0` turned out to be simple enough that I decided to backport it to the master branch, removing all dependencies on `atty` so that the advisory warning is no longer triggered.
The made-private `Node` type is essentially replaced with the newer `Compiled` type, and some function calls are restructured.
> update jsonpath-lib to 0.3.0, removing all atty deps

- examples/log_csv.yaml
- examples/random_search.yaml
- lib/config-gen/tests/test.js
- lib/config/src/configv2/common.rs
- lib/config/src/configv2/endpoints.rs
- lib/config/src/configv2/load_pattern.rs
- lib/config/src/configv2/mod.rs
- src/request/response_handler.rs
- [Lowered logging to debug when response can't be parsed as JSON. It was happening on ALL non-json responses](https://github.com/FamilySearch/pewpew/commit/a3cee58cb6d7470df583aecda090ecd4f598e231)
- [Updated formatting to round to hpm for rates or m or h for durations](https://github.com/FamilySearch/pewpew/commit/4607b3a7ff0174293aad7f42ba675245ac33a77d)
- [Removed unneeded space](https://github.com/FamilySearch/pewpew/commit/5c2ca26b87a9710d3a042d934f1190e8a594912a)
- [Updated the example to use a provider](https://github.com/FamilySearch/pewpew/commit/69d7c3efa515d3ae544e232ff934e48a2a33ede8)
- [Changed the order for the config gen to put load_patterns before config](https://github.com/FamilySearch/pewpew/commit/0de06b1dd20b857734e795aa9fbef179a97a7e74)
> Scripting updater formatting

- lib/config-gen/tests/wasm.rs
- lib/config-wasm/src/lib.rs
- lib/config-wasm/test-node.sh
- lib/config-wasm/tests/test.js
- lib/config/src/configv1/error.rs
- lib/config/src/configv2/error.rs
- lib/config/src/configv2/mod.rs
- lib/config/src/lib.rs
- [Added empty and json test](https://github.com/FamilySearch/pewpew/commit/04a3bc95d36b9b1af5a98ad2cf09b32a63785c58)
- [Added additional logging to debug config parser not erroring](https://github.com/FamilySearch/pewpew/commit/d053a718976a0c717d3178c1498502fca2aa37fd)
- [Added optional parameter to force either legacy or scripting parsing](https://github.com/FamilySearch/pewpew/commit/09fa525511a66a7d8e6a09f72bffb179c353ab57) 
- If the parameter is not passed it will attempt to parse yaml as both v1 and v2. If legacy is true it only parses v1, false only v2.
- [Added tests for the new optional config-wasm parameter to force legacy or scripting parsing](https://github.com/FamilySearch/pewpew/commit/f87d7af0917725ae436a1bef54408e556b2109e9)
- [Updated code to not support empty yaml …
> Config wasm no errors

- README.md
- deny.toml
- guide/build-guide.sh
- guide/serve-guide.sh
- lib/config-gen/tests/test.js
- lib/config/src/configv1/convert_helper.rs
- lib/config/src/configv1/expression_functions.rs
- lib/config/src/configv1/select_parser.rs
- lib/config/src/configv2/loggers.rs
- lib/config/src/configv2/query.rs
- lib/config/src/configv2/templating.rs
- lib/config/src/shared.rs
- lib/config/src/shared/encode.rs
- pewpew-config-updater/README.md
- Major improvements to the pewpew-config-updater. It will now do everything it can to try and leave the old expressions in and attempt to convert them over
- Known issues:
- Expressions in vars will not wrap environment variables in the expected `${e:VAR}`
- vars in `logs` and `provides` will not have the prepended `_v.` before the var name.
- Changed the order of `limit` in loggers
- Removed cargo deny ignore now that the dependency is removed
> Config updater improvements

- guide/src/cli.md
- src/bin/pewpew.rs
- src/lib.rs
- `-k`/`--skip-response-body` will only skip the response body
- `-K`/`--skip-request-body` will only skip the request body
- `-k -K` will skip BOTH request and response body
> Split the skipBody try parameter into separate request/response skip

- README.md
- examples/declare.yaml
- lib/config/src/configv1/convert_helper.rs
- lib/config/src/configv2/endpoints/declare.rs
- lib/config/src/configv2/error.rs
- lib/config/src/configv2/mod.rs
- lib/config/src/configv2/templating.rs
- tests/integration.yaml
- [Fixed the issue where vars cannot be floats](https://github.com/FamilySearch/pewpew/pull/171/commits/249f9244c3f1c20c34664e8bd8220631cb6dbbe9)
- [Fixed issue with trailing slash on Map Vars](https://github.com/FamilySearch/pewpew/pull/171/commits/4b151c967698db305be37efc1e6c79d876c4a955)
- [Added fixes for declare returning stringified json](https://github.com/FamilySearch/pewpew/pull/171/commits/a34bf2d6cab20b1d6c0c27a52e4190f2f2417625)
- Added fix for collect always returning stringified json if it is returning an array of objects
- Added fix for declare expressions that were escaping json in the declare
- Added example yaml that shows json in vars, declare, and collect objects
- [Added vars parsing of floating point to the integration …
> Scripting fixes20231027

- examples/provider_collect.yaml
- examples/provider_loop_with_counter.yaml
- examples/provider_spread.yaml
- lib/channel/src/lib.rs
- lib/config-wasm/tests/legacy_examples/provider_collect.yaml
- lib/config-wasm/tests/legacy_examples/provider_loop_with_counter.yaml
- lib/config-wasm/tests/legacy_examples/provider_spread.yaml
- src/lib.rs
- https://github.com/FamilySearch/pewpew/pull/177
> Try hang scripting

- common/src/s3file.ts
- common/src/util/s3.ts
- common/test/s3.spec.ts
- common/test/s3file.spec.ts
- controller/components/Layout/index.tsx
- controller/components/LinkButton/index.tsx
- controller/pages/api/search.ts
- controller/pages/api/util/ppaasencrypts3file.ts
- controller/pages/api/util/testmanager.ts
- controller/pages/index.tsx
- [Fixed an issue where searching for old tests that were yml failed to find](https://github.com/FamilySearch/pewpew/commit/199f63573f36f9001f7890132dc1c32e70f01202)
- Changed the s3 listFiles by extension and PPaasS3File getAllFilesInS3 to allow an extension array
- Changed the TestManager searchTests to search for both .yaml and .yml files when searching for old tests
- [Added code to handle an empty array](https://github.com/FamilySearch/pewpew/pull/184/commits/58b2555a75040832d325e55846d59434f5808e9e)
- [Added code to handle specify the extension(s) to the search page and the search on the index page](https://github.com/FamilySearch/pewpew/pull/184/commits/a08e3716d24a234b9ba7ffc6c6049da1e8effcdc)
- [Changed page load error to warn and log …
> Fixed an issue where searching for old tests that were yml failed to find

- agent/createtest/pewpewtest.spec.ts
- agent/src/pewpewtest.ts
- common/src/util/s3.ts
- controller/integration/testmanager.spec.ts
- controller/pages/api/util/testmanager.ts
- controller/pages/api/util/testscheduler.ts
- controller/policy/bucket-expiration-policy.xml
- controller/test/testscheduler.spec.ts
- [Added new tags for extra files from tests](https://github.com/FamilySearch/pewpew/pull/188/commits/7f05322d8a2e8d3d8bd2ee82e0316680dca275c8)
- Test files will be the yaml file, status file, and results files (these will be kept longer)
- Test Extra files will be log files, environment variables, and all other files needed by the yaml or logged by the yaml
- [Added code to tag extra files correctly](https://github.com/FamilySearch/pewpew/pull/188/commits/f7e17ecca6cd31017a0ef88fd85b8fcb76425fa8)
- Stdout, stderr, and all other files generated by the yaml will be tagged as Test Extra files and be tagged for deletion accordingly
- [Added code to tag extra files correctly](https://github.com/FamilySearch/pewpew/pull/188/commits/46a823b2670fececc22fe55502f6e91da125e99d)
- Additional files …
> Retain tests longer

- .github/actions/linux-x86_64-musl/Dockerfile
- .github/workflows/pr-guide.yml
- .github/workflows/pr-ppaas.yml
- .github/workflows/pr-rust.yml
- .github/workflows/release-test-server.yml
- .github/workflows/release.yml
- .github/workflows/update-guide.yml
- Cargo.lock
- guide/results-viewer-react/package-lock.json
- package-lock.json
- [Updated dependencies](https://github.com/FamilySearch/pewpew/pull/198/commits/51153f3c12f388aa3ffe6150cf8e60cfb769d36d)
- [Attempt to replace actions-rs with rustup](https://github.com/FamilySearch/pewpew/pull/198/commits/dcab9a6baa87adcd503b0ce17f3aacc0f2854058)
- https://github.com/actions-rs/toolchain/issues/216#issuecomment-1291613319
- Rustup is now available on default github runners, switch to using it. Consider https://github.com/Swatinem/rust-cache in the future
- [Removed some missed actions-rs lines](https://github.com/FamilySearch/pewpew/pull/198/commits/9f844b3e1e22a1dc83c621bef2f9a522feee51b2)
- [Added install of cross](https://github.com/FamilySearch/pewpew/pull/198/commits/bd32df1c829a407b361c66ce6fbd4a67528b3ff6)
- [Updated additional github actions to remove …
> Replace actions-rs with rustup

- .eslintrc
- controller/acceptance/healthcheck.spec.ts
- controller/acceptance/pewpew.spec.ts
- controller/acceptance/queues.spec.ts
- controller/acceptance/test.spec.ts
- controller/components/YamlWriterUpload/index.tsx
- controller/integration/pewpew.spec.ts
- guide/results-viewer-react/.eslintrc
- guide/results-viewer-react/src/components/YamlWriterUpload/index.tsx
- pr.sh
- [Updated pr script to prompt for coverage/acceptance tests](https://github.com/FamilySearch/pewpew/commit/2fb39df93fabe6710f8d65f62d67b6152de3b586)
- [Added no-tabs eslint rule and fix errors](https://github.com/FamilySearch/pewpew/commit/eec56504970eb7249d11cfe7c977776d4317850e)
- [Updated the pewpew acceptance and integration to match fixes in scripting](https://github.com/FamilySearch/pewpew/pull/214/commits/b1a7c48af27ac50321dd12b5aa8b4ff59e81824e)
[b1a7c48](https://github.com/FamilySearch/pewpew/pull/214/commits/b1a7c48af27ac50321dd12b5aa8b4ff59e81824e)
> Update pr script

- common/src/ppaasteststatus.ts
- common/src/util/s3.ts
- PPaasTestStatus.getAllStatus on the root s3 folder were finding tests from the shared subfolders on shared s3 buckets. It was then erroring when trying to load the status for those files
- Added export constant for the shared folder which can be overridden by SHARED_ENVIRONMENT_PREFIX env
- Added code to the getAllStatus function to ignore s3 keys that start with SHARED_ENVIRONMENT_PREFIX when our KEYSPACE_PREFIX is an empty string
> Fixed issue with shared s3 buckets

- common/src/ppaasteststatus.ts
- common/src/util/s3.ts
Merging https://github.com/FamilySearch/pewpew/pull/221 into the Scripting branch.
- PPaasTestStatus.getAllStatus on the root s3 folder were finding tests from the shared subfolders on shared s3 buckets. It was then erroring when trying to load the status for those files
- Added export constant for the shared folder which can be overridden by SHARED_ENVIRONMENT_PREFIX env
- Added code to the getAllStatus function to ignore s3 keys that start with SHARED_ENVIRONMENT_PREFIX when our KEYSPACE_PREFIX is an empty string
> Fixed issue with shared s3 buckets (#221)

- guide/build-guide.sh
- guide/serve-guide.sh
- guide/src/config/providers-section.md
- The example had endpoint rather than response
- Added some additional examples
> Fixed a typo in the provider docs

- guide/src/config/providers-section.md
- https://github.com/FamilySearch/pewpew/pull/227
- [Fixed the new examples for the scripting version](https://github.com/FamilySearch/pewpew/pull/228/commits/b468a459fa6a6fd4da9900c97b932da0f9571ad5)
> Fix provider typo scripting

- Cargo.lock
- lib/channel/Cargo.toml
- lib/channel/src/lib.rs
- lib/config/src/lib.rs
- lib/config/src/select_parser.rs
- src/request.rs
- src/stats.rs
- [Updated cargo lock file to latest versions](https://github.com/FamilySearch/pewpew/commit/4bdaf2dd7153508bfe40ee7bc117e52479a784ff)
- [Fixed clippy warnings](https://github.com/FamilySearch/pewpew/commit/1a8472ae58753d4ef8b426b0e94763899c66292d)
> Update rust dependencies 2024-07-18

- examples/.gitignore
- examples/body_file.yaml
- examples/body_formdata.yaml
- examples/body_json.yaml
- examples/body_multipart.yaml
- examples/delete_search.yaml
- examples/delete_sequential_404s.yaml
- examples/log_all.yaml
- examples/log_csv.yaml
- examples/log_errors.yaml
- examples/login_for_apis_block.yaml
- examples/login_for_apis_force_new.yaml
- examples/login_for_apis_on_demand.yaml
- examples/provider_chain.yaml
- examples/provider_collect.yaml
- examples/provider_create_and_delete.yaml
- examples/provider_grid.yaml
- examples/provider_loop.yaml
- examples/provider_loop_with_counter.yaml
- examples/provider_redirect.yaml
- examples/provider_spread.yaml
- examples/ramp_and_load.yaml
- examples/ramp_api_different.yaml
- examples/ramp_basic.yaml
- examples/ramp_over_time.yaml
- examples/ramp_to_scale.yaml
- examples/ramp_up_and_down.yaml
- examples/random_search.yaml
- examples/test_examples.sh
- examples/variables.sh
- [Added script to test the examples and script with example variables](https://github.com/FamilySearch/pewpew/commit/afd8c89bc7e41b06aa309672dd6468f558e67666)
- [Updated example files to send to stdout so test_examples can view actual errors](https://github.com/FamilySearch/pewpew/commit/af0282b552599e1b03577d9c068f960c44811c46)
- [Fixed the loggers for several broken examples](https://github.com/FamilySearch/pewpew/commit/e5e70656444d76b967b090bee6f09ba89f6bee8c)
> Update pewpew examples and test

- Cargo.lock
- src/request/request_maker.rs
- src/request/response_handler.rs
- [Added additional logging to the response handler](https://github.com/FamilySearch/pewpew/commit/b1ff1dc0080e4295610ae575d0f75a5efc6a4b43)
- [Fixed a bug from the hyper upgrade](https://github.com/FamilySearch/pewpew/commit/db9d796a00db9ce1031360ce3eb17339542a6d13)
- We were using hyper Response::new to just copy the body when we should've been using Response::from_parts which keeps the headers and status when converting from Incoming to BoxBody
- [Updated the Cargo.lock file to latest](https://github.com/FamilySearch/pewpew/commit/f943b25865117c4307220698dff370f56466878a)
> Fix response status and headers

- Cargo.lock
- lib/config-wasm/tests/legacy_examples/int_on_demand.yaml
- src/request/request_maker.rs
- src/request/response_handler.rs
- https://github.com/FamilySearch/pewpew/pull/245
- [Revert change to stdout to match master branch](https://github.com/FamilySearch/pewpew/pull/246/commits/19c1b564cf6921c8526cee8ef56ae1e0d112b47b)
> Fix response status and headers - scripting branch

- guide/results-viewer-react/package-lock.json
- guide/src/config/providers-section.md
- [Fixed the example in the docs to remove the dashes](https://github.com/FamilySearch/pewpew/commit/d60958ed06e26dde05f3b0c48ee226621944419a)
- [Updated the lock file to latest](https://github.com/FamilySearch/pewpew/commit/e5ffc070e364cd4e7c5fa79168184686367526fa)
> Fix provider docs

- .gitignore
- agent/package.json
- common/package.json
- controller/.storybook/main.ts
- controller/components/YamlEndpoints/index.tsx
- controller/components/YamlLoadPatterns/index.tsx
- controller/components/YamlLoggers/index.tsx
- controller/components/YamlProviders/index.tsx
- controller/components/YamlVars/index.tsx
- controller/next.config.ts
- controller/package.json
- guide/results-viewer-react/.storybook/main.ts
- guide/results-viewer-react/src/components/YamlEndpoints/index.tsx
- guide/results-viewer-react/src/components/YamlLoadPatterns/index.tsx
- guide/results-viewer-react/src/components/YamlLoggers/index.tsx
- guide/results-viewer-react/src/components/YamlProviders/index.tsx
- guide/results-viewer-react/src/components/YamlVars/index.tsx
- package-lock.json
- package.json
- [Fixed issue with storybook and webpack findDOMNode error](https://github.com/FamilySearch/pewpew/commit/59baf0e2f579308ac4baeeac013f077bfe29dcb5)
- With Next 15, we were getting some storybook errors about deprecated findDOMNode. The fix is to specify a nodeRef on TransitionGroups so findDOMNode is not called
- [Added webpack typings to next.js and storybook](https://github.com/FamilySearch/pewpew/commit/8e708d4d4ade3a7fc18b8512003b6dc1ec8d9813)
- [Updated version for release](https://github.com/FamilySearch/pewpew/commit/b6c787059c27a5a653025dc1d26ec7695634de51)
> Fix storybook webpack error

- .gitignore
- agent/package.json
- common/package.json
- controller/.storybook/main.ts
- controller/components/YamlEndpoints/index.tsx
- controller/components/YamlLoadPatterns/index.tsx
- controller/components/YamlLoggers/index.tsx
- controller/components/YamlProviders/index.tsx
- controller/components/YamlVars/index.tsx
- controller/next.config.ts
- controller/package.json
- guide/results-viewer-react/.storybook/main.ts
- guide/results-viewer-react/src/components/YamlEndpoints/index.tsx
- guide/results-viewer-react/src/components/YamlLoadPatterns/index.tsx
- guide/results-viewer-react/src/components/YamlLoggers/index.tsx
- guide/results-viewer-react/src/components/YamlProviders/index.tsx
- guide/results-viewer-react/src/components/YamlVars/index.tsx
- package-lock.json
- package.json
https://github.com/FamilySearch/pewpew/pull/267 into scripting branch
⚠️ DO NOT CLICK REBASE BRANCH ⚠️ 
* Fixed issue with storybook and webpack findDOMNode error
- With Next 15, we were getting some storybook errors about deprecated findDOMNode. The fix is to specify a nodeRef on TransitionGroups so findDOMNode is not called
* Added webpack typings to next.js and storybook
* Updated version for release
> Fix storybook webpack error (#267) Scripting

- controller/.storybook/main.ts
- controller/.storybook/preview.js
- controller/.storybook/tsconfig.json
- controller/components/TestResults/index.tsx
- controller/test/singleTestResult.js
- eslint.config.mjs
- guide/results-viewer-react/src/components/TestResults/index.tsx
- [Fixed the bug with multiple results files and switching between](https://github.com/FamilySearch/pewpew/commit/b6b6978bcce23a9e0a06c99cda4854498dc01fed)
- The null pointer throws on redraw. All the calculations and freeing of memory must be done within a setState block while the data is static
- [Updated eslint to include storybook](https://github.com/FamilySearch/pewpew/commit/a8574f3ec2992f56d20492ff2a89e84be9e1767b)
> Fix multiple test results bug

- guide/results-viewer-react/package-lock.json
- guide/results-viewer-react/package.json
- guide/results-viewer-react/src/components/YamlUrls/HeadersView.tsx
- guide/results-viewer-react/src/components/YamlUrls/RequestDetailsTabs.tsx
- guide/results-viewer-react/src/components/YamlUrls/ResponseView.tsx
- guide/results-viewer-react/src/components/YamlUrls/index.tsx
- package-lock.json
Made several updates and fixes, including:
- Fixed this issue: https://github.com/FamilySearch/pewpew/issues/263
- Added a script called `dev` for running `results-viewer-react`; renamed the original `dev` script to `dev-lint`
- Moved three YamlUrls subcomponents (`RequestDetailsTab`, `HeadersView`, and `ResponseView`) to their own files
- The Edit Endpoint modal opens when "Add Endpoint" is clicked
- The response now catches and displays CORS errors
- The Response tab opens when "Test" is clicked
> PewPew improvements

- guide/results-viewer-react/src/components/Modal/index.tsx
- guide/results-viewer-react/src/components/YamlUrls/QueryParamsView.tsx
- guide/results-viewer-react/src/components/YamlUrls/RequestBodyView.tsx
- guide/results-viewer-react/src/components/YamlUrls/RequestDetailsTabs.tsx
- guide/results-viewer-react/src/components/YamlUrls/index.tsx
- guide/results-viewer-react/src/util/yamlwriter.ts
The following bug fixes and features are implemented:
- Set Edit Endpoint modal to open w/o using a useEffect
- Reset that modal when the “Close” button is clicked
- Receive and use query parameters
- Request body can be created and used in requests
- Create a button to clear the URL field
- The option for devkey is removed
> PewRL fixes and updates

- agent/hooks/post-build/000-run-build
- agent/package.json
- common/integration/s3.spec.ts
- common/integration/sqs.spec.ts
- common/package.json
- common/src/util/s3.ts
- common/src/util/sqs.ts
- common/test/mock.ts
- common/tsconfig.lib.json
- controller/hooks/post-build/000-run-build
- controller/package.json
- controller/pages/api/util/clientutil.ts
- controller/pages/api/util/log.ts
- controller/pages/api/util/s3.ts
- controller/pages/index.tsx
- controller/test/mock.ts
- package-lock.json
- package.json
- [Updated prepare to only build release code](https://github.com/FamilySearch/pewpew/commit/4bde77b6a635a182ce08e30593d617cf44cc054f)
- [Fixed 1 hour limit on sqs and s3 when not in AWS](https://github.com/FamilySearch/pewpew/commit/496832e0087de19eb75a45c43db9a0e57dfaaa47)
- If running in AWS we still create a single s3 or sqs client that gets returned, but the config now is a function that returns that client
- If not running in AWS, we create an s3 or sqs client each time we need it and use the fromIni to not cached the credentials
- mock.ts now creates it's own mock instance and then creates an override function for the s3 or sqs config to return the mocked client
- [Updated lock file to latest](https://github.com/FamilySearch/pewpew/commit/681af38046c8151961e25dcb1e194a76520a3c67)
- …
> Fix controller crash

- controller/pages/api/error/[yamlFile]/[dateString]/index.ts
- controller/pages/api/json/[yamlFile]/[dateString]/[resultsFile].ts
- controller/pages/api/util/s3.ts
- controller/pages/index.tsx
- [Added fix for tests not running yet, don't load std error](https://github.com/FamilySearch/pewpew/commit/48c003c267e64310b6a8db13cec42fd3ff03054e)
- [Added code to s3 APIs to return 413 on large returnstroller.json](https://github.com/FamilySearch/pewpew/commit/b0b744a24dd0ee1dd8714a9012fc5f4dae80026a)
- By default Next.js just returns an empty string/body and 200 response (after a timeout) on large API responses. Default is 4MB.
- [Updated API's to allow a redirect parameter](https://github.com/FamilySearch/pewpew/commit/4c7353f351fa8c38e0730691e1285277d9adf3fd)
- The resultsFile and errorFile APIs will allow a ?redirect paramter to force redirect to S3 with a presigned url
- On the test status page if the console std error file returns a 413 it will add the ?redirect query param to …
> Fix large logfiles api

- agent/acceptance/tests.spec.ts
- agent/src/tests.ts
- common/src/index.ts
- common/src/ppaasteststatus.ts
- controller/pages/api/util/testmanager.ts
- [Added docs to a few functions](https://github.com/FamilySearch/pewpew/commit/92b2c90b6479257c8688763493eac142cf52dcf2)
- [Added common exports of all files](https://github.com/FamilySearch/pewpew/commit/60fed38f642cd5c2d14ed92ad1e843e8b0b74cb1)
- [Added option to have acceptance buildtest use the sqs queue](https://github.com/FamilySearch/pewpew/commit/86709b71682bcb916ead28d9e108c25532df3f6c)
- New optional environment variable ACCEPTANCE_SEND_TO_QUEUE. When set to truthy, the acceptance build test will put a test message on the sqs queue rather than run via API.
> Agent buildtest sqs

- agent/acceptance/tests.spec.ts
- agent/src/tests.ts
- common/src/index.ts
- common/src/ppaasteststatus.ts
- controller/pages/api/util/testmanager.ts
* Added docs to a few functions
* Added common exports of all files
* Added option to have acceptance buildtest use the sqs queue
- New optional environment variable ACCEPTANCE_SEND_TO_QUEUE. When set to truthy, the acceptance build test will put a test message on the sqs queue rather than run via API.
---------
> Agent buildtest sqs scripting

- .devcontainer/Dockerfile
- .github/workflows/pr-guide.yml
- .github/workflows/pr-rust.yml
- .github/workflows/update-guide.yml
- Cargo.lock
- Cargo.toml
- lib/body_reader/Cargo.toml
- lib/config-wasm/tests/package-lock.json
- lib/config-wasm/tests/package.json
- lib/config/Cargo.toml
- lib/hdr-histogram-wasm/tests/package-lock.json
- lib/hdr-histogram-wasm/tests/package.json
- lib/hdr-histogram-wasm/tests/test.js
- Updated all dependencies that we could without requiring Unicode 3.0 licenses
- Held back `unicode-ident` and `url` dependencies due to Unicode 3.0 license
- Held back `rand` and `getrandom` due to major code changes
- Updated PR flow (Dockerfile) dependencies
- Updated wasm Javascript tests dependencies to latest
- [Removed support for Node 18](https://github.com/FamilySearch/pewpew/pull/305/commits/ede6cab6b1db6beefe55c223ac0f912bc1ab1a07)
- Changed engine for tests to >20 due to Chai v5 requirements
> Update rust dependencies 2025-04-16

- .devcontainer/Dockerfile
- .github/workflows/pr-guide.yml
- .github/workflows/pr-rust.yml
- .github/workflows/update-guide.yml
- Cargo.lock
- Cargo.toml
- deny.toml
- lib/body_reader/Cargo.toml
- lib/config-wasm/tests/package-lock.json
- lib/config-wasm/tests/package.json
- lib/config/Cargo.toml
- lib/config/src/configv2/templating.rs
- lib/hdr-histogram-wasm/tests/package-lock.json
- lib/hdr-histogram-wasm/tests/package.json
- lib/hdr-histogram-wasm/tests/test.js
- pewpew-config-updater/Cargo.toml
- [Merge branch 'master' into update-rust-dependencies-scripting-2025-04-17](https://github.com/FamilySearch/pewpew/commit/6d4d856cf4fd38ded54ab06b14e352452ee5de17)
- https://github.com/FamilySearch/pewpew/pull/305
- Updated multiple packages to the latest versions
- [Updated env_logger and wasm-bindgen to latest](https://github.com/FamilySearch/pewpew/commit/edb062d59314dbc3b628c523d7e8d930007b1b35)
- [Updated thiserror to latest](https://github.com/FamilySearch/pewpew/commit/e0ea85316cf95bcc1ee9c78030ce691be991b30c)
- [Updated derive_more to latest](https://github.com/FamilySearch/pewpew/commit/2258db92ddfd48e680fbb1e90eb927b4189d3aae)
- [Fixed build warning](https://github.com/FamilySearch/pewpew/commit/f4802e7de28dbbf9e518b5d228f0c4f434713925)
- [Updated cargo deny until we can …
> Update rust dependencies scripting 2025-04-17
